[[secret_file]]
bws_name = "github-app-arc-id"
dest = "/Users/alex/komodo/runner-secrets/github-app-arc-id"

[[secret_file]]
bws_name = "github-app-arc-private-key"
dest = "/Users/alex/komodo/runner-secrets/github-app-arc-private-key"

[[secret_file]]
bws_name = "docker-hub-k3s-runner-api-key"
dest = "/Users/alex/komodo/runner-secrets/docker-hub-k3s-runner-api-key"

[[secret_file]]
bws_name = "github-pat-k3s-dean-gitops"
dest = "/Users/alex/komodo/runner-secrets/github-pat-k3s-dean-gitops"
