name: gpu-exporter-archlinux

services:
  amdgpu-exporter:
    image: rocm/device-metrics-exporter:latest
    container_name: amdgpu-exporter
    restart: unless-stopped
    ports:
      - "9101:2112"
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    group_add:
      - video
      - render
