#!/usr/bin/env bash
# Renders mac-mini-m4/automation/secrets.generated.yaml from BWS for Komodo deploy.
# Invoked by Komodo Periphery from the gitops repo root, so paths below are
# relative to that root. Mounted read-only into the HA container as
# /config/secrets.yaml (see compose.yaml) — consumed via `!secret <name>`.
set -euo pipefail

: "${BWS_ACCESS_TOKEN:?BWS_ACCESS_TOKEN required (cat /run/secrets/bws-access-token)}"

JELLYFIN_API_KEY=$(bws secret get "53080732-f813-46d7-b53d-b49801601e5d" \
    --access-token "$BWS_ACCESS_TOKEN" | jq -r .value | tr -d '[:space:]')
[[ -n "$JELLYFIN_API_KEY" && "$JELLYFIN_API_KEY" != "null" ]] \
  || { echo "automation pre-deploy: failed to fetch jellyfin-api-key" >&2; exit 1; }

SECRETS_FILE=mac-mini-m4/automation/secrets.generated.yaml

umask 077
cat > "$SECRETS_FILE" <<EOF
# Generated by pre-deploy.sh from BWS — do not edit, do not commit.
jellyfin_api_key: "${JELLYFIN_API_KEY}"
EOF

echo "automation pre-deploy: secrets.generated.yaml written"
